### ISSUE TITLE
Cant set Sidereal mode

### ISSUE THREAD

**Issue by iruleee** [vm75/sweph.dart#1]
When setting sidereal mode,
example: `sweph.swe_set_sid_mode(SiderealMode(1));`
It returns the following error:
`The following _TypeError was thrown attaching to the render tree:
type 'int' is not a subtype of type 'double'`

**Comment by vm75** [comment]
Thanks for raising the issue. It shows that my documentation needs clarifications. 
Please use sweph.swe_set_sid_mode(SiderealMode.SE_SIDM_LAHIRI) for your use case.

**Comment by iruleee** [comment]
Thanks for porting it to flutter, copied the example works perfectly. Had tried this earlier as well, dint work at the time. Thanks for sharing the example.

**Comment by prolaxu** [comment]
i am getting_TypeError
![Screenshot from 2022-08-20 18-35-20](https://user-images.githubusercontent.com/54370052/185746989-047b2f16-2a99-4e7c-a4ca-5b824e457431.png)


> Thanks for raising the issue. It shows that my documentation needs clarifications. Please use sweph.swe_set_sid_mode(SiderealMode.SE_SIDM_LAHIRI) for your use case.
