### ISSUE TITLE
Dart SDK support

### ISSUE THREAD

**Issue by jimmyff** [vm75/sweph.dart#16]
Hey, awesome work on this, just had a play and it's great! 

Just wondering about the decision to make this a Flutter package rather than a Dart package? Dart packages can be used in Flutter apps but Flutter packages cannot be used in Dart apps. As this has no UI a Dart package might be a better fit? If it's due to the asset loading you could either leave that to the user or you could create a `sweph-flutter` package which uses the core `sweph` dart package but adds on flutter asset loading? Is it something you could consider? It would be great to be able to use this in cloud-functions etc.

Thanks!

**Comment by vm75** [comment]
I want to do that. Don't get enough time. If you have a solution, do contribute.

**Comment by vm75** [comment]
I have added dart support. pub.dev doesn't show it correctly, but vanilla dart seems to work fine.
