### ISSUE TITLE
Feature request: Isolate support

### ISSUE THREAD

**Issue by offline-first** [vm75/sweph.dart#19]
Hello, thank you very much for the amazing library! It would be great if you could run the library in isolation. Unfortunately, the init function does not work and no error is returned when I try to run it in isolation. Do you have any idea what could be the reason for this?

**Comment by vm75** [comment]
Hi @offline-first , what do you mean by isolation? Do you mean dart mode?

**Comment by vm75** [comment]
I believe it is working now. Please try and let me know

**Comment by offline-first** [comment]
Hi @vm75 
I have updated to the latest version but now I get this error: 

```log
flutter: PathAccessException: Creation failed, path = './.test' (OS Error: Operation not permitted, errno = 1)
flutter: 
#0      _Directory.createSync (dart:io/directory_impl.dart:124:7)
#1      SwephPlatformProvider.init (package:sweph/src/ffi_provider.dart:39:15)
<asynchronous suspension>
#2      Sweph.init (package:sweph/sweph.dart:53:17)
<asynchronous suspension>
#3      initSweph (package:hdr/service/io_helper.dart:14:3)
<asynchronous suspension>
```
