### ISSUE TITLE
swe_house not return right output

### ISSUE THREAD

**Issue by prolaxu** [vm75/sweph.dart#2]
i tried to recreate script  written in python to  dart  but dart is returning different output please help me out
**dart**
```
Future<void> test() async{
  final sweph = Sweph();

  const year=1947;
  const month=8;
  const day=15;
  const hour = 16 + (0.0 / 60.0) - 5.5;

  const longitude = 81 + 50 / 60.0;
  const latitude = 25 +57/ 60.0;
  final julday = await sweph.swe_julday(year,month,day,hour,CalendarType.SE_GREG_CAL);

  sweph.swe_set_ephe_path('assets/ephe');
  sweph.swe_set_sid_mode(SiderealMode.SE_SIDM_LAHIRI, SiderealModeFlag.SE_SIDBIT_NONE, 0.0 /* t0 */, 0.0 /* ayan_t0 */);
  final ayanamsa =await sweph.swe_get_ayanamsa_ut(julday);
  final result = await sweph.swe_houses(julday,latitude, longitude,80);
  final ascmc=result.ascmc;
  print(ascmc);
}
```
**Dart  output:**
` [6.90179146357213e-310, 6.9017917270277e-310, 202.32377437705568, 141.5759100096468, 290.6418074130853, 300.3720274048396, 243.10677594481172, 120.37202740483966, 0.0, 0.0, 0.0, 0.0, 0.0]`

**python:**
```
import swisseph as swe
year = 1947
month = 8
day = 15

longitude = 81+50/60.0 #Allahabad
latitude = 25+57/60.0
hour = 16+(0.0/60.0)-5.5

julday = swe.julday(year, month, day, hour, swe.GREG_CAL)

swe.set_ephe_path('ephe')
swe.set_sid_mode(swe.SIDM_LAHIRI)

ayanamsa = swe.get_ayanamsa_ut(julday)

result = swe.houses(julday, latitude, longitude)
ascmc = result[1]
print(ascmc)

```
**Python output:**
`(279.5018682773932, 204.11199827584667, 202.32377437705568, 141.5759100096468, 290.6418074130853, 300.3720274048396, 243.10677594481172, 120.37202740483966)`

**Comment by vm75** [comment]
Hi,
Thanks for reporting and fixing the issue. Sorry for the delay in response. I will look into it and get your fix integrated.

**Comment by vm75** [comment]
I am using asTypedList a lot. If it is wrong in one place, likely it is broken in other places as well. Will look into it.
Thanks again

**Comment by vm75** [comment]
I tried adding your code to the example app and I am getting the same values as python. Could you please share an example app with the repro?

**Comment by vm75** [comment]
Not able to repro this.
