### ISSUE TITLE
Converting to a pure dart package

### ISSUE THREAD

**Issue by mrnags** [vm75/sweph.dart#20]
I saw the following in Sweph's change log 

//[3.0.0+2.10.3]  Converting to a pure dart package. Some changes to init and example. Modified versioning format. Now including sweph version as build number.//

Is it now also  a pure dart package? But, it is still listed only as a Flutter package and has Flutter SDK dependency in pubspec.yaml.

Can you help in publishing it also as a Dart package so that this package can be used in the Dart backend?

Thanks and Regards.

**Comment by vm75** [comment]
I did it the hacky/unsupported way.
It works just fine, but pub.dev doesn't recognize it because of the ffi-plugin directives in pubspec.yaml.
You can refer to example.dart. If you run into issues, do let me know.

**Comment by vm75** [comment]
There may be a more elegant way of achieving both. I will explore. If you know of one, let me know.

**Comment by mrnags** [comment]
Thanks. I will try and let you know.
