### ISSUE TITLE
custom `seorbel.txt` is not loaded with v3

### ISSUE THREAD

**Issue by timashev** [vm75/sweph.dart#22]
v3 ignores custom `seorbel.txt` – I load it like this:
```
Sweph.init(epheAssets: [
  ...
  'assets/ephe/seorbel.txt',
  ...
]);
```
With v2 it works, but as soon as I upgrade `sweph` to v3, I see: `Exception: error no elements for fictitious body no 23` (I have additional lines in my custom `seorbel.txt`) – this is on macOS and Web.

[On iOS and Android the app crashes during init!](https://github.com/vm75/sweph.dart/issues/21)

**Comment by vm75** [comment]
thanks for raising this issue @timashev , I will look into it

**Comment by vm75** [comment]
@timashev , help me reproduce this issue. I have added seorbel.txt to my init and am trying to test it on Android and iOS

**Comment by vm75** [comment]
I have updated the example to include 'assets/ephe/seorbel.txt' during init. it is tested on all platforms and works.
