### ISSUE TITLE
Seeing a few errors related to redefinition

### ISSUE THREAD

**Issue by madhavabhyankar** [vm75/sweph.dart#4]
There are a few errors specifically related to redefinition of *.  For example
`    In file included from /Users/madhav/projects/sdk/flutter/.pub-cache/hosted/pub.dartlang.org/sweph-2.10.02+8/ios/Classes/sweph.c:4:
    In file included from /Users/madhav/projects/sdk/flutter/.pub-cache/hosted/pub.dartlang.org/sweph-2.10.02+8/ios/Classes/../../native/apple-inc.c:2:
    In file included from /Users/madhav/projects/sdk/flutter/.pub-cache/hosted/pub.dartlang.org/sweph-2.10.02+8/ios/Classes/../../native/sweph/src/swedate.c:85:
    /Users/madhav/projects/sdk/flutter/.pub-cache/hosted/pub.dartlang.org/sweph-2.10.02+8/ios/Classes/../../native/sweph/src/sweph.h:701:8: error: redefinition of 'plantbl'
    struct plantbl {`

**Comment by vm75** [comment]
Hi, Sorry for the delay in response. 
~~I am unable to see these errors. Could you share the repro steps, including platform and compiler settings?~~
I just noticed that these are for ios and I don't have an Apple machine to build. 
I will see if it can be identified by looking at the code.
