### ISSUE TITLE
Can it support web?

### ISSUE THREAD

**Issue by softwareone2020** [vm75/sweph.dart#5]
The error is as follows,

../lib/src/sweph_wrapper.dart:3:8: Error: Not found: 'dart:ffi'
import 'dart:ffi';
       ^
../lib/src/sweph_bindings_generated.dart:9:8: Error: Not found: 'dart:ffi'
import 'dart:ffi' as ffi;
       ^
../lib/src/native_utils.dart:2:8: Error: Not found: 'dart:ffi'
import 'dart:ffi';
       ^
/C:/Users/One/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/ffi-2.0.1/lib/src/allocation.dart:5:8: Error: Not found: 'dart:ffi'
import 'dart:ffi';
       ^
/C:/Users/One/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/ffi-2.0.1/lib/src/arena.dart:8:8: Error: Not found: 'dart:ffi'
import 'dart:ffi';
       ^
...

Failed to compile application.

**Comment by vm75** [comment]
Hi,
Thanks for the ticket. Let me try to do something for web

**Comment by vm75** [comment]
unfortunately, the sweph library is very tightly coupled with file-io and porting to web is a challenge. I could think of using URL instead of path, open online file instead of local, etc., or ignore files altogether. But needs some deep factoring and presently, I am not up-to it.

**Comment by vm75** [comment]
Enabled Web :)

**Comment by softwareone2020** [comment]
Thank you so much :)
