### ISSUE TITLE
ResourceUtils.extractAssets()

### ISSUE THREAD

**Issue by craigjarman** [vm75/sweph.dart#7]
Hi

The 

`await ResourceUtils.extractAssets('assets/files/seas_18.se1', 'assets/ephe/seas_18.se1');`

fails on iOS.

Error is:

```
Exception has occurred.
FileSystemException (FileSystemException: Creation failed, path = 'assets' (OS Error: Read-only file system, errno = 30))
```

The following code is fine however.

```
Future<String> _initDefaultEpheFiles() async {
    const srcPath = 'packages/$_libName/native/sweph/src'; // asset path

    final filesToExtract = {
      'ast_list.txt': 'seasnam.txt',
      'sefstars.txt': 'sefstars.txt',
      'seleapsec.txt': 'seleapsec.txt',
    };

    final appDataDir = await getApplicationSupportDirectory();
    final libEphePath = '${appDataDir.path}/$_libName/${swe_version()}';

    for (final entry in filesToExtract.entries) {
      final dst = '$libEphePath/${entry.value}';
      if (!File(dst).existsSync()) {
        await ResourceUtils.extractAssets('$srcPath/${entry.key}', dst);
      }
    }

    return libEphePath;
  }
```

**Comment by vm75** [comment]
Hi Craig,
Thanks for the update.
Seems that the getApplicationSupportDirectory method in iOS returns a
protected folder.
I am thinking of removing the included files and letting users provide
their own.
What is your opinion?
Vijay

**Comment by craigjarman** [comment]
Hie Vijay,

In terms of letting users provide their, I presume this as I did previously. As follows:

```
 final filesToExtract = {
      'ast_list.txt': 'seasnam.txt',
      'sefstars.txt': 'sefstars.txt',
      'seleapsec.txt': 'seleapsec.txt',
      'seas_18.se1': 'seas_18.se1'
    };
```

We know this works. It just means digging into the plugin code to:

1. Update the filesToExtract list
2. Add the Ephemeris files

The approach you were aiming to achieve is ideal, but seems to to be running into a security barriers.

If the files can be pulled from an '/assets/ephemFiles' directory and written to the same target directory as is the 'astrology_list.text' file for example, then that should work.

```
**const srcPath = 'packages/$_libName/native/sweph/src'; // Can the srcPath = "/Assets/ephemFiles" instead?????**
final appDataDir = await getApplicationSupportDirectory();
    final libEphePath = '${appDataDir.path}/$_libName/${swe_version()}';

    for (final entry in filesToExtract.entries) {
      final dst = '$libEphePath/${entry.value}';
      if (!File(dst).existsSync()) {
        await ResourceUtils.extractAssets('$srcPath/${entry.key}', dst);
      }
    }
```

Otherwise, for now, I'd agree that having the dev manually include the required files is the best approach for the flowing reasons:

- It works...
- It allows for sync calls

Alternatively, can the required files simply be included along with the c-code? I'm pretty sure Swiss Ephemeris looks in at its own directory.

Thanks 

Craig

NB: Where are you located? As sin which time zone? I'm in Sydney., AU.

**Comment by vm75** [comment]
I am in the greater Seattle area (PST).
This is the first time I am actively maintaining a public github repository
and really appreciate all your help.

My fix for the example is very similar to what you have outlined here.
I tested it and it works on Android. Hopefully it should be working in iOS
as well.

One of the motivations for removing files is to remove flutter dependency
and make it a dart plugin.
Then the example can simply show how to add/manage assets as needed.
My only concern is that the frequent changes to the API may be irritating
for the consumers.

- Vijay

**Comment by craigjarman** [comment]
OK - Let me try the new version.

Thanks 

Craig

**Comment by craigjarman** [comment]
New error is

Exception has occurred.
_Exception (Exception: error, swe_fixstar(): could not find star name rohini)

From calling:

```
static String getStarName(Sweph sweph) {
    final jd = sweph.swe_julday(2022, 6, 29, (2 + 52 / 60), CalendarType.SE_GREG_CAL);
    return sweph.swe_fixstar2_ut('Rohini', jd, SwephFlag.SEFLG_SWIEPH)
//....

}
```

& also for Chiron.

Exception has occurred.
_Exception (Exception: SwissEph file 'seas_18.se1' not found in PATH '.:/users/ephe2/:/users/ephe/')

**Comment by vm75** [comment]
This is bad. Sorry about it.
I will get hold an ios device and try to fix it

**Comment by craigjarman** [comment]
Maybe, in the meantime, back it down to version 2.10.3+1.

And add in the House enums. Hys.P etc.

**Comment by vm75** [comment]
Does your code call either useDefaultEpheFiles or swe_set_ephe_path?
One of the two is necessary otherwise the sweph defaults are used:

/*
 * ephemeris path
 * this defines where ephemeris files are expected if the function
 * swe_set_ephe_path() is not called by the application.
 * Normally, every application should make this call to define its
 * own place for the ephemeris files.
 */

#ifndef SE_EPHE_PATH
#if MSDOS
#  define SE_EPHE_PATH    "\\sweph\\ephe\\"
#else
# ifdef MACOS
#  define SE_EPHE_PATH  ":ephe:"
# else
#  define SE_EPHE_PATH    ".:/users/ephe2/:/users/ephe/"
                        /* At Astrodienst, we maintain two ephemeris areas
for
                           the thousands of asteroid files:
                           the short files in /users/ephe/ast*,
                           the long file in /users/ephe2/ast*. */
# endif
#endif
#endif  /* SE_EPHE_PATH */

**Comment by vm75** [comment]
ignore my email.
it is my code!!!

**Comment by craigjarman** [comment]
Yes, I was just testing your example code.
I the set path the only issue?

**Comment by vm75** [comment]
yes, very sorry about it.
I realized as soon as I sent the email.
I suspect the path length in iOS may be the cause. sweph takes only paths
up-to 256 chars in length.
I have pushed out the changes.
Meanwhile, I will try to get hold of an iPhone +Mac to build and test.

Even if the example is not working for you, you should be able to test the
same with hardcoded paths in iOS.

**Comment by craigjarman** [comment]
Hi, The repository is still showing version 2.10.3+5

**Comment by vm75** [comment]
oops. I forgot to publish. did it now.

**Comment by craigjarman** [comment]
OK - same issue.

Exception has occurred.
_Exception (Exception: error, swe_fixstar(): could not find star name rohini)

I think version #1 is the best version to have as a production release.

**Comment by vm75** [comment]
I finally got hold of a Mac Mini and an iPhone 8.
I was able to setup the dev environment and ran the example of iOS
simulator successfully. I did not run into any errors. On building, some
build files got generated and I guess I may have to add them to the example
project.

To run it on the iPhone i believe I need a developer account. Hopefully I
should be able to test it.

**Comment by vm75** [comment]
Ah, being an Apple developer is not free!!
I will have to make-do with the simulator.

Are you hitting the error with the simulator as well?


[image: image.png]

**Comment by craigjarman** [comment]
Hi, Yes, I hit in in the Simulator when using the example code.

**Comment by vm75** [comment]
Verified working on iPhone-8 as well.
My setup: Mac Mini M1 with macOS 13.1 & iPhone 8 with iOS 13.1.3
Brand new setup :) since I started from scratch. Learned a bunch about
Apple dev.

Something seems to be different in your setup.
Could you please try flutter clean and then run?

[image: image.png]

**Comment by vm75** [comment]
Also, I had to install something called cocoapods without which flutter was
failing.
That generated a bunch of pod files which I will have to add to the ios/mac
projects
